version: '3.7'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: changemenow
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    user: mysql

  zookeeper:
    image: wurstmeister/zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
    depends_on:
      - zookeeper

#  jobmanager:
#    image: flink:latest
#    command: jobmanager
#    ports:
#      - "8082:8082"
#    environment:
#      - JOB_MANAGER_RPC_ADDRESS=jobmanager
#
#  taskmanager:
#    image: flink:latest
#    command: taskmanager
#    depends_on:
#      - jobmanager

volumes:
  mysql-data:
