apiVersion: v1
kind: ConfigMap
metadata:
  name: urlshortener-config
data:
  application.properties: |
    spring.datasource.url=jdbc:mysql://mysql:3306/mydb
    spring.datasource.username=root
    spring.datasource.password=${MYSQL_ROOT_PASSWORD}
    spring.kafka.bootstrap-servers=kafka:9092
    spring.kafka.consumer.group-id=urlshortener-events
