apiVersion: v1
kind: Service
metadata:
  labels:
    urlshortener: jobmanager
  name: jobmanager
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
  selector:
    urlshortener: jobmanager
