apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    urlshortener: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      urlshortener: kafka
  template:
    metadata:
      labels:
        urlshortener: kafka
    spec:
      containers:
        - env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:9092
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "false"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
          image: wurstmeister/kafka
          name: kafka
          ports:
            - containerPort: 9092
              protocol: TCP
      restartPolicy: Always
