apiVersion: v1
kind: Service
metadata:
  labels:
    independent: kafka
  name: kafka-node-port
spec:
  type: NodePort
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
      nodePort: 30092
  selector:
    urlshortener: kafka
