apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    urlshortener: mysql-data
  name: mysql-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
