apiVersion: v1
kind: Service
metadata:
  labels:
    independent: mysql
  name: mysql-node-port
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30306  # Choose a port in the range 30000-32767
  selector:
    urlshortener: mysql

