apiVersion: v1
kind: Service
metadata:
  labels:
    urlshortener: urlshortener-service
  name: urlshortener-service
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    urlshortener: urlshortener-service
