apiVersion: v1
kind: Service
metadata:
  labels:
    urlshortener: urlshortener-statistics
  name: urlshortener-statistics
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    urlshortener: urlshortener-statistics
