apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    urlshortener: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      urlshortener: zookeeper
  template:
    metadata:
      labels:
        urlshortener: zookeeper
    spec:
      containers:
        - env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_SERVER_ID
              value: "1"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          image: wurstmeister/zookeeper
          name: zookeeper
          ports:
            - containerPort: 2181
              protocol: TCP
      restartPolicy: Always
