apiVersion: v1
kind: Service
metadata:
  labels:
    urlshortener: zookeeper
  name: zookeeper
spec:
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
  selector:
    urlshortener: zookeeper
